---
- name: Tomcat deployment
  hosts: tomcat
  gather_facts: true
  become: yes
  become_method: sudo
  remote_user: adminuser
  vars:
    tomcat_ver: 10.1.19
    tomcat_v_num: 10 # Tomcat major release number,
    ui_manager_user: manager # User who can access the UI manager section only
    ui_manager_pass: Str0ngManagerP@ssw3rd # UI manager user password
    ui_admin_username: admin # User who can access bpth manager and admin UI sections
    ui_admin_pass: Str0ngAdminP@ssw3rd # UI admin password
  roles:
    - tomcat

- name: Sonar deployment
  hosts: sonar
  become: yes
  gather_facts: true
  become_method: sudo
  remote_user: adminuser
  roles:
    - sonar

- name: Docker installation
  hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - docker
  
- name: Azure cli installation
  hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - azurecli

- name: Jenkins deployment
  hosts: localhost
  become: yes
  gather_facts: true
  become_method: sudo
  roles:
    - jenkins

