---
- name: Check host distribution
  debug:
    msg: "Distribution is {{ ansible_distribution }}"

- name: Update jenkins  server
  apt:
    update_cache: yes

- name: Install OpenJDK-17-jre
  apt:
    name:
      - fontconfig
      - openjdk-17-jre

- name: Check java version
  shell: java -version
  register: java_version

- debug:
    msg: "{{ java_version.stderr_lines }}"

- name: Download Jenkins GPG key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc

- name: Add Jenkins repository to Apt sources
  shell: echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

- name: Update docker server
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name:
      - jenkins
